language: python
python:
    - "3.5"
    - "3.6"

env:
    - "TASK=lint"
    - "TASK=test_travis"

before_install:
    - "pip install pytest coveralls flake8"

install:
    - "pip install -r requirements.txt"
    - "pip install ."

script:
    - "make $TASK"
